# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))

# -- Project information -----------------------------------------------------

project = u'PROS for V5（中文）'
copyright = u'2019 Purdue ACM SIGBots 根据 MPL 2.0 许可发布，MechDancer 译。'
author = u'Purdue ACM SIGBots, MechDancer'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = u'V5 (3.1.6)'
# The full version, including alpha/beta/rc tags.
release = u'3.1.6'

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = []

# Add any paths that contain templates here, relative to this directory.
templates_path = ['page_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'zh_CN'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
import sphinx_rtd_theme
html_theme = 'sphinx_rtd_theme'
html_context = {
    'display_github': True,
    'github_user': 'MechDancer',
    'github_repo': 'pros-docs',
    'github_version': 'master/v5-chinese/'
}
html_theme_options = {
    'analytics_id': 'UA-84548828-3',
    'versions': {
        'V5': 'index',
        'Cortex': '../cortex/index',
    },
    'navigation_depth': 8
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = "../common/images/logo.svg"
html_favicon = "../common/_static/favicon.ico"

# html_title = ""
html_additional_pages = {
    #'index': 'index.html'
}

html_show_sphinx = False
highlight_language = "c"
nitpicky = True

blog_path = 'blog/index'
